generatorName: csharp
additionalProperties:
  packageName: Invokation.Skill.Sdk
  targetFramework: net8.0
  library: httpclient
  useCollection: true
  nullableReferenceTypes: true
  useDateTimeOffset: true
  optionalEmitDefaultValues: false
  conditionalSerialization: true
  optionalMethodArgument: true
  generateApiDocumentation: true
  generateModelDocumentation: true
